sonar.projectKey=xavlkh_ModuleGo
sonar.organization=xavlkh
sonar.projectName=ModuleGo
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,app/static/local-data/data/**
sonar.test.inclusions=tests/test_*.py

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
