apiVersion: v1
kind: Service
metadata:
  name: modulego
  namespace: modulego
spec:
  selector:
    app: modulego
  ports:
    - port: 5000
      targetPort: 5000
  # NodePort exposes the app on the minikube node's IP.
  type: NodePort
