apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: modulego
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  # ClusterIP — only reachable from inside the cluster.
  type: ClusterIP
